### PR TITLE
[cloud_firestore] fix NoSuchMethodError regression and add test

### PR DESCRIPTION
**Pull request by collinjackson**
Fixes a `NoSuchMethodError` in getDocuments(), introduced in #1339

Adds a simple driver test for the fix.

Fixes flutter/flutter#29423

### CODE REVIEW

File: packages/cloud_firestore/example/test_driver/cloud_firestore.dart [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  group('$Firestore', () {
+    Firestore firestore;
+
+    setUp(() async {
+      final FirebaseApp app = await FirebaseApp.configure(
+        name: 'test',
+        options: const FirebaseOptions(
+          googleAppID: '1:79601577497:ios:5f2bcc6ba8cecddd',
+          gcmSenderID: '79601577497',
+          apiKey: 'AIzaSyArgmRGfB5kiQT6CunAOmKRVKEsxKmy6YI-G72PVU',
```
Comment (amirh) [inline packages/cloud_firestore/example/test_driver/cloud_firestore.dart]: Is this a real API key that anyone can use?

File: packages/cloud_firestore/CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+## 0.9.7
+
+* Fixes an iOS regression in getDocuments introduced in 0.9.6.
```
Comment (amirh) [inline packages/cloud_firestore/CHANGELOG.md]: Would be useful to describe what was the regression (both here and in the PR description)

File: packages/cloud_firestore/example/test_driver/cloud_firestore.dart (hunk 1 above)
Comment (collinjackson) [reply packages/cloud_firestore/example/test_driver/cloud_firestore.dart]: Yes, it's the same credentials used by the example app. We can lock down the permissions on the server side.
